<a href="https://colab.research.google.com/github/EgLang/FeatureExtraction/blob/main/Feature_Extraction_For_Fault_Identification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install h5py pandas google-cloud-bigquery google-cloud-storage

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
from google.cloud import storage

# Initialize the Google Cloud Storage client
storage_client = storage.Client()

# Specify your bucket name
bucket_name = 'fault_identification_vvv_data'  # Replace with your actual bucket name

# Get the bucket object
bucket = storage_client.bucket(bucket_name)

# List all files in the bucket
blobs = list(bucket.list_blobs())  # Convert the iterator to a list


In [ ]:
import os

# Directory to save downloaded files
local_directory = '/content/downloaded_files'
os.makedirs(local_directory, exist_ok=True)

# Download each file in the bucket
for blob in blobs:
    local_file_path = os.path.join(local_directory, blob.name)
    # Ensure the local directory structure matches the bucket's
    os.makedirs(os.path.dirname(local_file_path), exist_ok=True)
    blob.download_to_filename(local_file_path)
    print(f'File {blob.name} downloaded to {local_file_path}.')

print('All files downloaded.')

File mydata100.h5 downloaded to /content/downloaded_files/mydata100.h5.
File mydata1000.h5 downloaded to /content/downloaded_files/mydata1000.h5.
File mydata1100.h5 downloaded to /content/downloaded_files/mydata1100.h5.
File mydata1200.h5 downloaded to /content/downloaded_files/mydata1200.h5.
File mydata1300.h5 downloaded to /content/downloaded_files/mydata1300.h5.
File mydata1400.h5 downloaded to /content/downloaded_files/mydata1400.h5.
File mydata1500.h5 downloaded to /content/downloaded_files/mydata1500.h5.
File mydata1600.h5 downloaded to /content/downloaded_files/mydata1600.h5.
File mydata1700.h5 downloaded to /content/downloaded_files/mydata1700.h5.
File mydata1800.h5 downloaded to /content/downloaded_files/mydata1800.h5.
File mydata1900.h5 downloaded to /content/downloaded_files/mydata1900.h5.
File mydata200.h5 downloaded to /content/downloaded_files/mydata200.h5.
File mydata2000.h5 downloaded to /content/downloaded_files/mydata2000.h5.
File mydata2100.h5 downloaded to /content/

In [ ]:

local_directory = '/content/downloaded_files'

# List all files in the local directory
downloaded_files = [os.path.join(local_directory, f) for f in os.listdir(local_directory) if os.path.isfile(os.path.join(local_directory, f))]

print("Downloaded files:")
for file in downloaded_files:
    print(file)

Downloaded files:
/content/downloaded_files/mydata1200.h5
/content/downloaded_files/mydata5800.h5
/content/downloaded_files/mydata5400.h5
/content/downloaded_files/mydata500.h5
/content/downloaded_files/mydata1000.h5
/content/downloaded_files/mydata3900.h5
/content/downloaded_files/mydata3700.h5
/content/downloaded_files/mydata2400.h5
/content/downloaded_files/mydata1100.h5
/content/downloaded_files/mydata3000.h5
/content/downloaded_files/mydata3100.h5
/content/downloaded_files/mydata2100.h5
/content/downloaded_files/mydata2600.h5
/content/downloaded_files/mydata200.h5
/content/downloaded_files/mydata3500.h5
/content/downloaded_files/mydata1800.h5
/content/downloaded_files/mydata4000.h5
/content/downloaded_files/mydata5700.h5
/content/downloaded_files/mydata6000.h5
/content/downloaded_files/mydata4300.h5
/content/downloaded_files/mydata4200.h5
/content/downloaded_files/mydata5100.h5
/content/downloaded_files/mydata3600.h5
/content/downloaded_files/mydata4700.h5
/content/downloaded_file

In [ ]:
import h5py

def list_hdf5_paths(file_path):
    paths = []
    def append_path(name, obj):
        paths.append(name)
    with h5py.File(file_path, 'r') as f:
        f.visititems(append_path)
    return paths

# Iterate over each file and list the paths
all_paths = {}
for file_path in downloaded_files:
    paths = list_hdf5_paths(file_path)
    all_paths[file_path] = paths
    print(f"\nPaths in {file_path}:")
    for path in paths:
        print(path)


Paths in /content/downloaded_files/mydata1200.h5:
data_set

Paths in /content/downloaded_files/mydata5800.h5:
data_set

Paths in /content/downloaded_files/mydata5400.h5:
data_set

Paths in /content/downloaded_files/mydata500.h5:
data_set

Paths in /content/downloaded_files/mydata1000.h5:
data_set

Paths in /content/downloaded_files/mydata3900.h5:
data_set

Paths in /content/downloaded_files/mydata3700.h5:
data_set

Paths in /content/downloaded_files/mydata2400.h5:
data_set

Paths in /content/downloaded_files/mydata1100.h5:
data_set

Paths in /content/downloaded_files/mydata3000.h5:
data_set

Paths in /content/downloaded_files/mydata3100.h5:
data_set

Paths in /content/downloaded_files/mydata2100.h5:
data_set

Paths in /content/downloaded_files/mydata2600.h5:
data_set

Paths in /content/downloaded_files/mydata200.h5:
data_set

Paths in /content/downloaded_files/mydata3500.h5:
data_set

Paths in /content/downloaded_files/mydata1800.h5:
data_set

Paths in /content/downloaded_files/mydata

In [ ]:
import h5py
import numpy as np

def load_and_transpose_data_from_hdf5(file_path, dataset_path):
    with h5py.File(file_path, 'r') as f:
        data = f[dataset_path][:]
    transposed_data = np.transpose(data)
    return transposed_data

# Common dataset path (replace with the correct path if different)
dataset_path = '/data_set'  # Example path, replace with your actual path

# Load, transpose, and store data from each file into a list
all_transposed_data = []

for file_path in downloaded_files:
    transposed_data = load_and_transpose_data_from_hdf5(file_path, dataset_path)
    all_transposed_data.append(transposed_data)

# Verify the transposed data
print(f"Number of datasets collected: {len(all_transposed_data)}")

# Display the shape of each transposed dataset
for i, data in enumerate(all_transposed_data):
    print(f"Shape of transposed dataset {i}: {data.shape}")

Number of datasets collected: 62
Shape of transposed dataset 0: (100, 50006)
Shape of transposed dataset 1: (100, 50006)
Shape of transposed dataset 2: (100, 50006)
Shape of transposed dataset 3: (100, 50006)
Shape of transposed dataset 4: (100, 50006)
Shape of transposed dataset 5: (100, 50006)
Shape of transposed dataset 6: (100, 50006)
Shape of transposed dataset 7: (100, 50006)
Shape of transposed dataset 8: (100, 50006)
Shape of transposed dataset 9: (100, 50006)
Shape of transposed dataset 10: (100, 50006)
Shape of transposed dataset 11: (100, 50006)
Shape of transposed dataset 12: (100, 50006)
Shape of transposed dataset 13: (100, 50006)
Shape of transposed dataset 14: (100, 50006)
Shape of transposed dataset 15: (100, 50006)
Shape of transposed dataset 16: (100, 50006)
Shape of transposed dataset 17: (100, 50006)
Shape of transposed dataset 18: (100, 50006)
Shape of transposed dataset 19: (100, 50006)
Shape of transposed dataset 20: (100, 50006)
Shape of transposed dataset 21: 

In [ ]:
# Concatenate all transposed datasets into a single NumPy array
combined_transposed_data = np.vstack(all_transposed_data)  # Use np.hstack(all_transposed_data) if you want to concatenate horizontally

# Verify the shape of the combined transposed data
print(f"Shape of combined transposed data: {combined_transposed_data.shape}")

# Inspect the first few rows of the combined transposed data
print("First few rows of combined transposed data:")
print(combined_transposed_data)

Shape of combined transposed data: (6125, 50006)
First few rows of combined transposed data:
[[0.         0.         0.         ... 0.75       0.625      0.375     ]
 [0.         0.         0.         ... 0.75       0.625      0.375     ]
 [0.         0.         0.         ... 0.75       0.625      0.375     ]
 ...
 [0.         0.         0.         ... 0.53696942 0.46713734 0.59298532]
 [0.         0.         0.         ... 0.63575612 0.30155726 0.72552154]
 [0.         0.         0.         ... 0.49927027 0.31080523 0.61857071]]


In [ ]:
X = combined_transposed_data[:, 0:50001]
Y = combined_transposed_data[:, 50003]

In [ ]:
print(X)

[[0.         0.         0.         ... 7.53293783 7.5445816  7.5562672 ]
 [0.         0.         0.         ... 6.98865988 6.99953874 7.01043193]
 [0.         0.         0.         ... 6.36672416 6.37817512 6.38966271]
 ...
 [0.         0.         0.         ... 6.8849425  6.89668158 6.90840651]
 [0.         0.         0.         ... 8.66344377 8.68160608 8.69971848]
 [0.         0.         0.         ... 7.55337216 7.56354297 7.57369439]]


In [ ]:
print(len(X))

6125


In [ ]:
print(Y)

[0.75       0.75       0.75       ... 0.53696942 0.63575612 0.49927027]


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Assuming X is a NumPy array
# Standardize the data
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split



# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.05, random_state=42)



In [ ]:
from sklearn.decomposition import PCA

# Apply PCA
pca = PCA(n_components=20, svd_solver='full')  # Adjust n_components to the number of principal components you want
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__


'2.15.0'

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=80, activation='tanh'))
ann.add(tf.keras.layers.Dense(units=1, activation='linear'))
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
ann.fit(X_train_pca, y_train, batch_size = 256, epochs = 2000)

Epoch 1/2000
23/23 [==============================] - 2s 3ms/step - loss: 0.5080
Epoch 2/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0826
Epoch 3/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0336
Epoch 4/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0191
Epoch 5/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0150
Epoch 6/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0124
Epoch 7/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0106
Epoch 8/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0092
Epoch 9/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0081
Epoch 10/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0071
Epoch 11/2000
23/23 [==============================] - 0s 2ms/step - loss: 0.0063
Epoch 12/2000
23/23 [==============================] - 0s 3ms/step - loss: 0.0057
Epoch 13/2000
23/23 [====

In [ ]:
print(y_test)

[0.56089711 0.31521785 0.55667552 0.375      0.25       0.625
 0.25       0.68706078 0.28296858 0.44937125 0.375      0.5
 0.35769278 0.5        0.25       0.33914192 0.625      0.41250817
 0.25       0.5        0.28561389 0.25       0.75       0.25
 0.375      0.37852267 0.625      0.41093785 0.625      0.66769504
 0.29930347 0.625      0.69410079 0.625      0.67369382 0.39247279
 0.25       0.25979118 0.375      0.625      0.35149293 0.71711783
 0.5        0.625      0.625      0.625      0.625      0.625
 0.75       0.27058768 0.75       0.5        0.71587581 0.375
 0.5        0.53917349 0.375      0.71864442 0.25       0.625
 0.375      0.54975649 0.625      0.53273518 0.75       0.75
 0.5        0.375      0.625      0.30707125 0.42951334 0.5
 0.70327041 0.58609312 0.625      0.37739062 0.51123888 0.6306124
 0.71666573 0.25       0.375      0.64019164 0.6061195  0.625
 0.51089625 0.70749979 0.71262356 0.6883328  0.75       0.25
 0.75       0.75       0.75       0.375      0.375   

In [ ]:
# Reshape the array to 2D format
y_test = np.expand_dims(y_test, axis=1)

In [ ]:
print(y_test)

[[0.56089711]
 [0.31521785]
 [0.55667552]
 [0.375     ]
 [0.25      ]
 [0.625     ]
 [0.25      ]
 [0.68706078]
 [0.28296858]
 [0.44937125]
 [0.375     ]
 [0.5       ]
 [0.35769278]
 [0.5       ]
 [0.25      ]
 [0.33914192]
 [0.625     ]
 [0.41250817]
 [0.25      ]
 [0.5       ]
 [0.28561389]
 [0.25      ]
 [0.75      ]
 [0.25      ]
 [0.375     ]
 [0.37852267]
 [0.625     ]
 [0.41093785]
 [0.625     ]
 [0.66769504]
 [0.29930347]
 [0.625     ]
 [0.69410079]
 [0.625     ]
 [0.67369382]
 [0.39247279]
 [0.25      ]
 [0.25979118]
 [0.375     ]
 [0.625     ]
 [0.35149293]
 [0.71711783]
 [0.5       ]
 [0.625     ]
 [0.625     ]
 [0.625     ]
 [0.625     ]
 [0.625     ]
 [0.75      ]
 [0.27058768]
 [0.75      ]
 [0.5       ]
 [0.71587581]
 [0.375     ]
 [0.5       ]
 [0.53917349]
 [0.375     ]
 [0.71864442]
 [0.25      ]
 [0.625     ]
 [0.375     ]
 [0.54975649]
 [0.625     ]
 [0.53273518]
 [0.75      ]
 [0.75      ]
 [0.5       ]
 [0.375     ]
 [0.625     ]
 [0.30707125]
 [0.42951334]
 [0.5 

In [ ]:
y_pred = ann.predict(X_test_pca)
# Calculate error
error = y_test - y_pred
sqd_error = (error)**2

10/10 [==============================] - 0s 2ms/step


In [ ]:
print(y_pred)

[[0.5530883 ]
 [0.31623328]
 [0.551115  ]
 [0.36736307]
 [0.25416392]
 [0.6223053 ]
 [0.25883165]
 [0.6865431 ]
 [0.27595216]
 [0.45093894]
 [0.3720404 ]
 [0.4962757 ]
 [0.35805354]
 [0.5009929 ]
 [0.2508467 ]
 [0.3408836 ]
 [0.6276542 ]
 [0.41053337]
 [0.2415666 ]
 [0.50038904]
 [0.28805673]
 [0.25192723]
 [0.7570151 ]
 [0.25068024]
 [0.36596343]
 [0.3743072 ]
 [0.6163447 ]
 [0.4109595 ]
 [0.63032544]
 [0.6710663 ]
 [0.30304927]
 [0.6215192 ]
 [0.6945108 ]
 [0.627431  ]
 [0.67499995]
 [0.39083767]
 [0.24900022]
 [0.26331288]
 [0.37170777]
 [0.62457687]
 [0.3462769 ]
 [0.7172737 ]
 [0.49881345]
 [0.6207965 ]
 [0.62019914]
 [0.6231654 ]
 [0.62626296]
 [0.62904274]
 [0.73481774]
 [0.26475102]
 [0.668296  ]
 [0.500826  ]
 [0.71917593]
 [0.37237453]
 [0.4977954 ]
 [0.5380525 ]
 [0.3717012 ]
 [0.7197304 ]
 [0.24911037]
 [0.622164  ]
 [0.36538234]
 [0.55665636]
 [0.6199057 ]
 [0.52516156]
 [0.7518494 ]
 [0.7532579 ]
 [0.49587062]
 [0.38057357]
 [0.6223757 ]
 [0.30682972]
 [0.42540562]
 [0.50

In [ ]:
# Calculate mean error, standard deviation, minimum, and maximum of the error
mean_error = np.mean(sqd_error, axis=0)
std_error = np.std(error, axis=0)
min_error = np.min(error, axis=0)
max_error = np.max(error, axis=0)
# Print results
print("Mean Error:", mean_error)
print("Standard Deviation of Error:", std_error)
print("Minimum Error:", min_error)
print("Maximum Error:", max_error)

Mean Error: [7.65295718e-05]
Standard Deviation of Error: [0.00868623]
Minimum Error: [-0.05082047]
Maximum Error: [0.08170402]
